//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColetorMobileTecware.WsTecware {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsTecware.WsColetorSoap")]
    public interface WsColetorSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ColetorMobileTecware.WsTecware.HelloWorldResponse HelloWorld(ColetorMobileTecware.WsTecware.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name xmlReturnResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/xmlReturn", ReplyAction="*")]
        ColetorMobileTecware.WsTecware.xmlReturnResponse xmlReturn(ColetorMobileTecware.WsTecware.xmlReturnRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ColetorMobileTecware.WsTecware.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ColetorMobileTecware.WsTecware.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ColetorMobileTecware.WsTecware.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ColetorMobileTecware.WsTecware.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class xmlReturnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="xmlReturn", Namespace="http://tempuri.org/", Order=0)]
        public ColetorMobileTecware.WsTecware.xmlReturnRequestBody Body;
        
        public xmlReturnRequest() {
        }
        
        public xmlReturnRequest(ColetorMobileTecware.WsTecware.xmlReturnRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class xmlReturnRequestBody {
        
        public xmlReturnRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class xmlReturnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="xmlReturnResponse", Namespace="http://tempuri.org/", Order=0)]
        public ColetorMobileTecware.WsTecware.xmlReturnResponseBody Body;
        
        public xmlReturnResponse() {
        }
        
        public xmlReturnResponse(ColetorMobileTecware.WsTecware.xmlReturnResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class xmlReturnResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement xmlReturnResult;
        
        public xmlReturnResponseBody() {
        }
        
        public xmlReturnResponseBody(System.Xml.XmlElement xmlReturnResult) {
            this.xmlReturnResult = xmlReturnResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface WsColetorSoapChannel : ColetorMobileTecware.WsTecware.WsColetorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WsColetorSoapClient : System.ServiceModel.ClientBase<ColetorMobileTecware.WsTecware.WsColetorSoap>, ColetorMobileTecware.WsTecware.WsColetorSoap {
        
        public WsColetorSoapClient() {
        }
        
        public WsColetorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsColetorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsColetorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsColetorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ColetorMobileTecware.WsTecware.HelloWorldResponse ColetorMobileTecware.WsTecware.WsColetorSoap.HelloWorld(ColetorMobileTecware.WsTecware.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ColetorMobileTecware.WsTecware.HelloWorldRequest inValue = new ColetorMobileTecware.WsTecware.HelloWorldRequest();
            inValue.Body = new ColetorMobileTecware.WsTecware.HelloWorldRequestBody();
            ColetorMobileTecware.WsTecware.HelloWorldResponse retVal = ((ColetorMobileTecware.WsTecware.WsColetorSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ColetorMobileTecware.WsTecware.xmlReturnResponse ColetorMobileTecware.WsTecware.WsColetorSoap.xmlReturn(ColetorMobileTecware.WsTecware.xmlReturnRequest request) {
            return base.Channel.xmlReturn(request);
        }
        
        public System.Xml.XmlElement xmlReturn() {
            ColetorMobileTecware.WsTecware.xmlReturnRequest inValue = new ColetorMobileTecware.WsTecware.xmlReturnRequest();
            inValue.Body = new ColetorMobileTecware.WsTecware.xmlReturnRequestBody();
            ColetorMobileTecware.WsTecware.xmlReturnResponse retVal = ((ColetorMobileTecware.WsTecware.WsColetorSoap)(this)).xmlReturn(inValue);
            return retVal.Body.xmlReturnResult;
        }
    }
}
