

SELECT TOP (10) codigoPROPOSTA,numeroPROPOSTA, CONVERT(nvarchar, P.dataLIBERACAOPROPOSTA,103)  +' '+ CONVERT(nvarchar, P.dataLIBERACAOPROPOSTA,108) as dataLIBERACAOPROPOSTA,clientePROPOSTA AS clientePROPOSTA, razaoEMPRESA ,
COALESCE(ordemseparacaoimpressaPROPOSTA,0) AS ordemseparacaoimpressaPROPOSTA, P.prioridadeLIBERACAOPROPOSTA,0 as volumesPROPOSTA
FROM tb1601_Propostas (NOLOCK) 
INNER JOIN tb1611_Liberacoes_Proposta P (NOLOCK) ON P.propostaLIBERACAOPROPOSTA = codigoPROPOSTA 
LEFT JOIN tb1611_Liberacoes_Proposta C (NOLOCK) ON C.propostaLIBERACAOPROPOSTA = codigoPROPOSTA 
LEFT JOIN tb0301_Empresas (NOLOCK) ON clientePROPOSTA = codigoEMPRESA
WHERE statusPROPOSTA = 1 
AND P.liberacaoLIBERACAOPROPOSTA = 1 
AND C.liberacaoLIBERACAOPROPOSTA = 2 
AND P.liberadoLIBERACAOPROPOSTA = 1  
AND C.liberadoLIBERACAOPROPOSTA = 0
AND P.prioridadeLIBERACAOPROPOSTA >= 0
ORDER BY  P.prioridadeLIBERACAOPROPOSTA ASC,P.dataLIBERACAOPROPOSTA ASC


update tb1611_Liberacoes_Proposta
set prioridadeLIBERACAOPROPOSTA = 1
where propostaLIBERACAOPROPOSTA in(
80457,
80396,
80466,
80471,
76698,
80446,
75899)


SELECT TOP 1 codigoPROPOSTA,numeroPROPOSTA,dataLIBERACAOPROPOSTA,clientePROPOSTA,razaoEMPRESA,volumesPROPOSTA 
FROM vwMobile_tb1601_Proposta  
ORDER BY  Prioridade ASC,dataLIBERACAOPROPOSTA ASC 



---                            ////////////////EXEMPLOS /////////////////////////

--NÃO UTILIZO ESTE SELECT POIS EXISTE DUPLICIDADE DE DADOS.
SELECT codigoITEMPROPOSTA,propostaITEMPROPOSTA,produtoRESERVA AS codigoPRODUTO,nomePRODUTO,partnumberPRODUTO,ean13PRODUTO,SUM(quantidadeRESERVA) AS QTD 
,loteRESERVA,localLOTELOCAL,nomeLOCAL
FROM tb1206_Reservas (NOLOCK) 
INNER JOIN tb1602_Itens_Proposta (NOLOCK) ON codigoITEMPROPOSTA = docRESERVA 
INNER JOIN tb0501_Produtos (NOLOCK) ON produtoITEMPROPOSTA = codigoPRODUTO
LEFT JOIN tb1212_Lotes_Locais (NOLOCK) ON loteRESERVA = loteLOTELOCAL
LEFT JOIN tb1211_Locais ON codigoLOCAL = localLOTELOCAL
WHERE propostaITEMPROPOSTA = 80471
AND tipodocRESERVA = 1602 
AND statusITEMPROPOSTA = 3 
AND separadoITEMPROPOSTA = 0  
GROUP BY codigoITEMPROPOSTA,propostaITEMPROPOSTA,ean13PRODUTO,produtoRESERVA,produtoITEMPROPOSTA,nomePRODUTO,
         partnumberPRODUTO,loteRESERVA,localLOTELOCAL,nomeLOCAL
ORDER BY nomeLOCAL ASC


--ESTE SELECT É UTILIZADO PARA RETORNAR INFORMAÇÕES DOS ITENS DAS PROPOSTAS.
SELECT codigoITEMPROPOSTA,propostaITEMPROPOSTA,produtoRESERVA AS codigoPRODUTO,nomePRODUTO,partnumberPRODUTO,ean13PRODUTO,SUM(quantidadeRESERVA) AS QTD
FROM tb1206_Reservas (NOLOCK) 
INNER JOIN tb1602_Itens_Proposta (NOLOCK) ON codigoITEMPROPOSTA = docRESERVA 
INNER JOIN tb0501_Produtos (NOLOCK) ON produtoITEMPROPOSTA = codigoPRODUTO 
LEFT JOIN tb1212_Lotes_Locais (NOLOCK) ON loteRESERVA = loteLOTELOCAL 
LEFT JOIN tb1211_Locais ON codigoLOCAL = localLOTELOCAL 
WHERE propostaITEMPROPOSTA = 80471
AND tipodocRESERVA = 1602 
AND statusITEMPROPOSTA = 3 
AND separadoITEMPROPOSTA = 0  
GROUP BY codigoITEMPROPOSTA,propostaITEMPROPOSTA,ean13PRODUTO,produtoRESERVA,produtoITEMPROPOSTA,
nomePRODUTO,partnumberPRODUTO

--PNUMBER:8098|DESCRICAO:Terminal Femea Jst 3.96 Fio 0.3 X 0.6|EAN13:7895479034365|LOTE:LT-01|SEQ:12340|QTD:2α

SELECT TOP (1) codigoPROPOSTA,numeroPROPOSTA,dataLIBERACAOPROPOSTA,clientePROPOSTA,razaoEMPRESA,volumesPROPOSTA 
FROM vwMobile_tb1601_Proposta 
ORDER BY  Prioridade ASC,dataLIBERACAOPROPOSTA ASC 


UPDATE tb1651_Picking_Mobile
SET statusPICKINGMOBILE =0
WHERE codigoPICKINGMOBILE =21

UPDATE tb1601_Propostas
SET statusProposta =1
WHERE codigoPROPOSTA = 75899

SELECT * FROM tb1651_Picking_Mobile
DELETE FROM tb1651_Picking_Mobile
SELECT MAX(codigoPICKINGMOBILE) AS maxCodigo FROM tb1651_Picking_Mobile WHERE propostaPICKINGMOBILE = 80457


SELECT TOP (1) codigoPROPOSTA,numeroPROPOSTA,dataLIBERACAOPROPOSTA,razaoEMPRESA,volumesPROPOSTA,codigoPICKINGMOBILE
FROM vwMobile_tb1601_Proposta 
ORDER BY  Prioridade ASC,dataLIBERACAOPROPOSTA ASC 

INSERT INTO tb1651_Picking_Mobile(propostaPICKINGMOBILE,usuarioPICKINGMOBILE,statusPICKINGMOBILE,horainicioPICKINGMOBILE,horafimPICKINGMOBILE) 
VALUES (80396,'114','1','8/28/2015 4:04:37 PM',NULL)


UPDATE tb1651_Picking_Mobile 
SET[statusPICKINGMOBILE] = 1,
[horafimPICKINGMOBILE] = NULL 
WHERE propostaPICKINGMOBILE = 80396  AND codigoPICKINGMOBILE = 18


                SELECT codigoITEMPROPOSTA,propostaITEMPROPOSTA,produtoRESERVA AS codigoPRODUTO,nomePRODUTO,partnumberPRODUTO,statusITEMPROPOSTA,
                ean13PRODUTO,SUM(quantidadeRESERVA) AS QTD
                FROM tb1206_Reservas (NOLOCK) 
                INNER JOIN tb1602_Itens_Proposta (NOLOCK) ON codigoITEMPROPOSTA = docRESERVA 
                INNER JOIN tb0501_Produtos (NOLOCK) ON produtoITEMPROPOSTA = codigoPRODUTO 
                LEFT JOIN tb1212_Lotes_Locais (NOLOCK) ON loteRESERVA = loteLOTELOCAL 
                LEFT JOIN tb1211_Locais ON codigoLOCAL = localLOTELOCAL 
				WHERE propostaITEMPROPOSTA  < 80461
                AND tipodocRESERVA = 1602 
                --AND statusITEMPROPOSTA = 3 
                AND separadoITEMPROPOSTA <>1  
                GROUP BY codigoITEMPROPOSTA,propostaITEMPROPOSTA,ean13PRODUTO,produtoRESERVA,produtoITEMPROPOSTA,statusITEMPROPOSTA,
                nomePRODUTO,partnumberPRODUTO
				ORDER BY codigoPRODUTO DESC


				SELECT codigoITEMPROPOSTA,propostaITEMPROPOSTA,statusseparadoITEMPROPOSTA,codigoprodutoITEMPROPOSTA,xmlSequenciaITEMPROPOSTA  
				FROM tb0002_ItensProposta 
				WHERE  statusseparadoITEMPROPOSTA = 1

				select * from tb1651_Picking_Mobile
				delete FROM tb1651_Picking_Mobile

				UPDATE tb1651_Picking_Mobile
				SET statusPIcKINGMOBILE = 0
                WHERE codigoPICKINGMOBILE = 1085

				--PROP 75899---
				--ITENS
				--1143211,1143212,1150875

				UPDATE tb1602_Itens_Proposta
				SET separadoITEMPROPOSTA = 0
				WHERE codigoITEMPROPOSTA IN (1143211,1143212,1150875)


				SELECT codigoITEMPROPOSTA,propostaITEMPROPOSTA,produtoITEMPROPOSTA,quantidadeITEMPROPOSTA,statusITEMPROPOSTA,separadoITEMPROPOSTA,xmlsequenciaITEMPROPOSTA 
				FROM tb1602_Itens_Proposta 
				WHERE propostaITEMPROPOSTA = 75899 AND codigoITEMPROPOSTA IN (1143211,1143212,1150875)

				UPDATE tb1651_Picking_Mobile 
				SET[statusPICKINGMOBILE] = 2,[horafimPICKINGMOBILE] = 8/31/2015 1:58:39 PM
				WHERE propostaPICKINGMOBILE =  AND codigoPICKINGMOBILE = 0

				UPDATE tb1651_Picking_Mobile
				SET[statusPICKINGMOBILE] = 2,[horafimPICKINGMOBILE] = '8/31/2015 2:45:12 PM' 
				WHERE propostaPICKINGMOBILE = 75899  AND codigoPICKINGMOBILE = 1046



SELECT SUM(quantidadeRESERVA) AS QTD
FROM tb1206_Reservas (NOLOCK)
INNER JOIN tb1602_Itens_Proposta (NOLOCK) ON codigoITEMPROPOSTA = docRESERVA
INNER JOIN tb0501_Produtos (NOLOCK) ON produtoITEMPROPOSTA = codigoPRODUTO 
INNER JOIN tb0504_Embalagens_Produtos ON codigoPRODUTO = produtoEMBALAGEMPRODUTO
LEFT JOIN tb1212_Lotes_Locais (NOLOCK) ON loteRESERVA = loteLOTELOCAL 
LEFT JOIN tb1211_Locais ON codigoLOCAL = localLOTELOCAL 
WHERE propostaITEMPROPOSTA = 80471 
AND tipodocRESERVA = 1602 
AND statusITEMPROPOSTA = 3
AND separadoITEMPROPOSTA = 0  
GROUP BY codigoITEMPROPOSTA


SELECT dbo.fn1211_SplitTitanium(1597,80471)
SELECT dbo.fnSplitTitanium('52776,52788')
SELECT * FROM  dbo.SplitTitanium('52776,52788',',')

	SELECT nomeLOCAL 
	FROM tb1205_Lotes
	INNER JOIN tb1212_Lotes_Locais ON codigoLOTE = loteLOTELOCAL
	INNER JOIN tb1211_Locais ON codigoLOCAL = localLOTELOCAL
	WHERE codigoLOTE IN (SELECT * FROM  dbo.SplitTitanium(dbo.fn1211_LotesReservaProduto(1597,80471),',') ) AND produtoLOTE = 1597
	ORDER BY nomeLOCAL ASC




SELECT codigoITEMPROPOSTA,propostaITEMPROPOSTA,produtoRESERVA AS codigoPRODUTO,nomePRODUTO,partnumberPRODUTO,ean13PRODUTO,SUM(quantidadeRESERVA) AS QTD
,quantidadeEMBALAGEMPRODUTO AS QtdEmbalagem
,dbo.fn1211_LotesReservaProduto(produtoRESERVA,propostaITEMPROPOSTA) AS lotesRESERVA
,DBO.fn1211_LocaisLoteProduto(produtoRESERVA,dbo.fn1211_LotesReservaProduto(produtoRESERVA,propostaITEMPROPOSTA)) AS locaisLOTES
FROM tb1206_Reservas (NOLOCK)
INNER JOIN tb1602_Itens_Proposta (NOLOCK) ON codigoITEMPROPOSTA = docRESERVA
INNER JOIN tb0501_Produtos (NOLOCK) ON produtoITEMPROPOSTA = codigoPRODUTO 
INNER JOIN tb0504_Embalagens_Produtos ON codigobarrasEMBALAGEMPRODUTO = ean13PRODUTO
LEFT JOIN tb1212_Lotes_Locais (NOLOCK) ON loteRESERVA = loteLOTELOCAL 
LEFT JOIN tb1211_Locais ON codigoLOCAL = localLOTELOCAL 
WHERE propostaITEMPROPOSTA = 80471 
AND tipodocRESERVA = 1602 
AND statusITEMPROPOSTA = 3
AND separadoITEMPROPOSTA = 0  
GROUP BY codigoITEMPROPOSTA,propostaITEMPROPOSTA,ean13PRODUTO,produtoRESERVA,nomePRODUTO,partnumberPRODUTO
,quantidadeEMBALAGEMPRODUTO,codigobarrasEMBALAGEMPRODUTO
ORDER BY codigoPRODUTO


SELECT codigoEMBALAGEMPRODUTO,nomeEMBALAGEMPRODUTO,produtoEMBALAGEMPRODUTO,quantidadeEMBALAGEMPRODUTO,padraoEMBALAGEMPRODUTO,embalagemEMBALAGEMPRODUTO,codigobarrasEMBALAGEMPRODUTO
, nomePRODUTO, quantidadeEMBALAGEMPRODUTO
FROM tb0501_Produtos
INNER JOIN tb0504_Embalagens_Produtos ON codigoPRODUTO = produtoEMBALAGEMPRODUTO
WHERE produtoEMBALAGEMPRODUTO IN(
									SELECT produtoRESERVA AS codigoPRODUTO
									FROM tb1206_Reservas (NOLOCK)
									INNER JOIN tb1602_Itens_Proposta (NOLOCK) ON codigoITEMPROPOSTA = docRESERVA
									INNER JOIN tb0501_Produtos (NOLOCK) ON produtoITEMPROPOSTA = codigoPRODUTO 
									WHERE propostaITEMPROPOSTA = 80471 
									AND tipodocRESERVA = 1602 
									AND statusITEMPROPOSTA = 3
									AND separadoITEMPROPOSTA = 0 
									GROUP BY produtoRESERVA
                                 )
AND lixeiraPRODUTO = 0
ORDER BY produtoEMBALAGEMPRODUTO


SELECT codigoEMBALAGEMPRODUTO,nomeEMBALAGEMPRODUTO,produtoEMBALAGEMPRODUTO,quantidadeEMBALAGEMPRODUTO,padraoEMBALAGEMPRODUTO,embalagemEMBALAGEMPRODUTO,codigobarrasEMBALAGEMPRODUTO
FROM tb0504_Embalagens_Produtos 
INNER JOIN tb0501_Produtos ON codigoPRODUTO = produtoEMBALAGEMPRODUTO
WHERE produtoEMBALAGEMPRODUTO IN(
									SELECT produtoRESERVA AS codigoPRODUTO
									FROM tb1206_Reservas (NOLOCK)
									INNER JOIN tb1602_Itens_Proposta (NOLOCK) ON codigoITEMPROPOSTA = docRESERVA
									INNER JOIN tb0501_Produtos (NOLOCK) ON produtoITEMPROPOSTA = codigoPRODUTO 
									WHERE propostaITEMPROPOSTA = 80471 
									AND tipodocRESERVA = 1602 
									AND statusITEMPROPOSTA = 3
									AND separadoITEMPROPOSTA = 0 
									GROUP BY produtoRESERVA
                                 )
AND lixeiraPRODUTO = 0
ORDER BY produtoEMBALAGEMPRODUTO




CREATE FUNCTION tb

SELECT produtoRESERVA AS codigoPRODUTO
FROM tb1206_Reservas (NOLOCK)
INNER JOIN tb1602_Itens_Proposta (NOLOCK) ON codigoITEMPROPOSTA = docRESERVA
INNER JOIN tb0501_Produtos (NOLOCK) ON produtoITEMPROPOSTA = codigoPRODUTO 
--LEFT JOIN tb1212_Lotes_Locais (NOLOCK) ON loteRESERVA = loteLOTELOCAL 
--LEFT JOIN tb1211_Locais ON codigoLOCAL = localLOTELOCAL 
WHERE propostaITEMPROPOSTA = 80471 
AND tipodocRESERVA = 1602 
AND statusITEMPROPOSTA = 3
AND separadoITEMPROPOSTA = 0 
GROUP BY produtoRESERVA


select DBO.fn1211_LocaisLoteProduto(codigoPRODUTO,LOTEreserva)
SELECT dbo.fn0504_Embalagem(9892, 0, 500, 4) as QtbEmbalagemPadrao
SELECT * FROM  tb0545_Embalagens
SELECT * FROM sys.objects o where o.name like'%Embalage%' 
select dbo.fn1602_Embalagens(9892,'Quantidade')

SP_HELPTEXT fn1211_LocaisLoteProduto

SELECT COALESCE(SUM(quantidadeRESERVA),0) AS QTD, separadoITEMPROPOSTA  
FROM tb1206_Reservas 
INNER JOIN tb1602_Itens_Proposta ON codigoITEMPROPOSTA = docRESERVA 
WHERE produtoRESERVA = 1559 AND propostaITEMPROPOSTA = 75899 
AND tipodocRESERVA = 1602 
AND statusITEMPROPOSTA = 3 
GROUP BY separadoITEMPROPOSTA


SELECT TOP 1 codigoPRODUTO, partnumberPRODUTO, nomePRODUTO, pathIMAGEMPRODUTO, quantidadeEMBALAGEMPRODUTO ,ean13PRODUTO,codigobarrasEMBALAGEMPRODUTO
FROM tb0501_Produtos 
INNER JOIN tb0504_Embalagens_Produtos ON codigoPRODUTO = produtoEMBALAGEMPRODUTO 
LEFT JOIN tb0520_Imagens_Produtos ON codigoPRODUTO = produtosIMAGEMPRODUTO 
WHERE produtoEMBALAGEMPRODUTO = 9869
--codigobarrasEMBALAGEMPRODUTO = '7895479026650' 
AND COALESCE(padraoIMAGEMPRODUTO,1) = 1 
AND lixeiraPRODUTO = 0


SELECT  codigoPRODUTO, partnumberPRODUTO, nomePRODUTO, pathIMAGEMPRODUTO, quantidadeEMBALAGEMPRODUTO ,ean13PRODUTO,codigobarrasEMBALAGEMPRODUTO
FROM tb0501_Produtos 
INNER JOIN tb0504_Embalagens_Produtos ON codigoPRODUTO = produtoEMBALAGEMPRODUTO 
LEFT JOIN tb0520_Imagens_Produtos ON codigoPRODUTO = produtosIMAGEMPRODUTO 
WHERE produtoEMBALAGEMPRODUTO = 2625
--codigobarrasEMBALAGEMPRODUTO = '7895479026650' 
AND COALESCE(padraoIMAGEMPRODUTO,1) = 1 
AND lixeiraPRODUTO = 0


SELECT codigoITEMPROPOSTA,propostaITEMPROPOSTA,produtoRESERVA AS codigoPRODUTO,nomePRODUTO,partnumberPRODUTO,ean13PRODUTO,
SUM(quantidadeRESERVA) AS QTD,quantidadeEMBALAGEMPRODUTO AS QtdEmbalagem,
dbo.fn1211_LotesReservaProduto(produtoRESERVA,propostaITEMPROPOSTA) AS lotesRESERVA,
DBO.fn1211_LocaisLoteProduto(produtoRESERVA,dbo.fn1211_LotesReservaProduto(produtoRESERVA,propostaITEMPROPOSTA)) AS locaisLOTES 
FROM tb1206_Reservas (NOLOCK) 
INNER JOIN tb1602_Itens_Proposta (NOLOCK) ON codigoITEMPROPOSTA = docRESERVA 
INNER JOIN tb0501_Produtos (NOLOCK) ON produtoITEMPROPOSTA = codigoPRODUTO  
INNER JOIN tb0504_Embalagens_Produtos ON codigobarrasEMBALAGEMPRODUTO = ean13PRODUTO 
LEFT JOIN tb1212_Lotes_Locais (NOLOCK) ON loteRESERVA = loteLOTELOCAL  
LEFT JOIN tb1211_Locais ON codigoLOCAL = localLOTELOCAL
WHERE propostaITEMPROPOSTA = 80471  
AND tipodocRESERVA = 1602  
AND statusITEMPROPOSTA = 3 
AND separadoITEMPROPOSTA = 0   
GROUP BY codigoITEMPROPOSTA,propostaITEMPROPOSTA,ean13PRODUTO,produtoRESERVA,nomePRODUTO,partnumberPRODUTO ,
quantidadeEMBALAGEMPRODUTO,codigobarrasEMBALAGEMPRODUTO
ORDER BY codigoPRODUTO





SELECT codigoITEMPROPOSTA,propostaITEMPROPOSTA,produtoRESERVA AS codigoPRODUTO,nomePRODUTO,partnumberPRODUTO,
ean13PRODUTO,[codigobarrasEMBALAGEMPRODUTO],
SUM(quantidadeRESERVA) AS QTD
,quantidadeEMBALAGEMPRODUTO,LOTEreserva
,DBO.fn1211_LocaisLoteProduto(produtoRESERVA,LOTEreserva) AS LOCAIS
FROM tb1206_Reservas (NOLOCK)
--,LOTEreserva
INNER JOIN tb1602_Itens_Proposta (NOLOCK) ON codigoITEMPROPOSTA = docRESERVA
INNER JOIN tb0501_Produtos (NOLOCK) ON produtoITEMPROPOSTA = codigoPRODUTO 
INNER JOIN tb0504_Embalagens_Produtos ON codigoPRODUTO = produtoEMBALAGEMPRODUTO
LEFT JOIN tb1212_Lotes_Locais (NOLOCK) ON loteRESERVA = loteLOTELOCAL 
LEFT JOIN tb1211_Locais ON codigoLOCAL = localLOTELOCAL 
WHERE propostaITEMPROPOSTA = 75899 
AND tipodocRESERVA = 1602 
AND statusITEMPROPOSTA = 3
AND separadoITEMPROPOSTA = 0  
GROUP BY codigoITEMPROPOSTA,propostaITEMPROPOSTA,ean13PRODUTO,produtoRESERVA,produtoITEMPROPOSTA,
nomePRODUTO,partnumberPRODUTO,embalagemITEMPROPOSTA
,quantidadeEMBALAGEMPRODUTO,LOTEreserva, [codigobarrasEMBALAGEMPRODUTO]



SELECT * FROM tb0504_Embalagens_Produtos WHERE produtoEMBALAGEMPRODUTO = 2155



SELECT codigoEMBALAGEMPRODUTO,nomeEMBALAGEMPRODUTO,produtoEMBALAGEMPRODUTO,quantidadeEMBALAGEMPRODUTO,padraoEMBALAGEMPRODUTO,embalagemEMBALAGEMPRODUTO,codigobarrasEMBALAGEMPRODUTO 
FROM tb0504_Embalagens_Produtos 
INNER JOIN tb0501_Produtos ON codigoPRODUTO = produtoEMBALAGEMPRODUTO 
WHERE produtoEMBALAGEMPRODUTO IN(
									SELECT produtoRESERVA AS codigoPRODUTO	
									FROM tb1206_Reservas (NOLOCK)
									INNER JOIN tb1602_Itens_Proposta (NOLOCK) ON codigoITEMPROPOSTA = docRESERVA
									INNER JOIN tb0501_Produtos (NOLOCK) ON produtoITEMPROPOSTA = codigoPRODUTO
									WHERE propostaITEMPROPOSTA = 75899
									AND tipodocRESERVA = 1602
									AND statusITEMPROPOSTA = 3
									AND separadoITEMPROPOSTA = 0
									GROUP BY produtoRESERVA                                 
								) AND 
lixeiraPRODUTO = 0 
ORDER BY produtoEMBALAGEMPRODUTO



SELECT codigoEMBALAGEMPRODUTO,nomeEMBALAGEMPRODUTO,produtoEMBALAGEMPRODUTO,quantidadeEMBALAGEMPRODUTO,padraoEMBALAGEMPRODUTO,embalagemEMBALAGEMPRODUTO,codigobarrasEMBALAGEMPRODUTO 
FROM tb0504_Embalagens_Produtos 
INNER JOIN tb0501_Produtos ON codigoPRODUTO = produtoEMBALAGEMPRODUTO 
WHERE produtoEMBALAGEMPRODUTO IN(
									SELECT produtoRESERVA AS codigoPRODUTO
									FROM tb1206_Reservas (NOLOCK)
									INNER JOIN tb1602_Itens_Proposta (NOLOCK) ON codigoITEMPROPOSTA = docRESERVA
									INNER JOIN tb0501_Produtos (NOLOCK) ON produtoITEMPROPOSTA = codigoPRODUTO
									WHERE propostaITEMPROPOSTA = 80396
									AND tipodocRESERVA = 1602 
									AND statusITEMPROPOSTA = 3
									AND separadoITEMPROPOSTA = 0
									GROUP BY produtoRESERVA                                 
									
									) 
									AND lixeiraPRODUTO = 0 
									ORDER BY produtoEMBALAGEMPRODUTO


SELECT codigoEMBALAGEMPRODUTO,COALESCE(nomeEMBALAGEMPRODUTO,'ND') AS nomeEMBALAGEMPRODUTO ,produtoEMBALAGEMPRODUTO,quantidadeEMBALAGEMPRODUTO,padraoEMBALAGEMPRODUTO,embalagemEMBALAGEMPRODUTO,
codigobarrasEMBALAGEMPRODUTO 
FROM tb0504_Embalagens_Produtos 
INNER JOIN tb0501_Produtos ON codigoPRODUTO = produtoEMBALAGEMPRODUTO 
WHERE produtoEMBALAGEMPRODUTO IN(
									SELECT produtoRESERVA AS codigoPRODUTO
									FROM tb1206_Reservas (NOLOCK)
									INNER JOIN tb1602_Itens_Proposta (NOLOCK) ON codigoITEMPROPOSTA = docRESERVA
									INNER JOIN tb0501_Produtos (NOLOCK) ON produtoITEMPROPOSTA = codigoPRODUTO
									WHERE propostaITEMPROPOSTA = 80396
									AND tipodocRESERVA = 1602
									AND statusITEMPROPOSTA = 3
									AND separadoITEMPROPOSTA = 0
									GROUP BY produtoRESERVA                                 
								) AND lixeiraPRODUTO = 0 ORDER BY produtoEMBALAGEMPRODUTO


